### ISSUE TITLE
Fehlende Attribution

### ISSUE THREAD

**Issue by skade** [dresden-community/dresden-code-of-conduct.org#1]
Hallo,

Ich melde mich als Maintainer des [Berlin Code of Conduct](http://berlincodeofconduct.org) und Vorstand des Ruby Berlin e.V. Wir freuen uns sehr, dass unser lokales Promotions-Modell und Text adaptiert wird und würden euch auch gerne unterstützen. Der Berlin Code of Conduct ist ein lebendes Dokument, das hin und wieder Anpassungen erfährt, wir freuen uns da natürlich über Gespräche.

Es ist allerdings aufgefallen, dass Ihr die Lizenz-Nennung aus dem Text entfernt habt und die Lizenz geändert habt.

Der Berlin Code of Conduct steht (wie der pdx.rb-CoC, auf dem er basiert) unter [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/). Diese verlangt Namensnennung und Unveränderlichbarkeit der Lizenz. Ich kann keine Attribution auf der Webseite finden und die Lizenz hier ist MIT (eine für Texte eigentlich nicht gedachte Lizenz) Kenntnismachung von Änderungen sehen wir durch das öffentliche Repository abgedeckt.

Es würde uns freuen, wenn ihr das nachtragt.

Mit besten Grüßen aus Berlin,
Florian

**Comment by hollodotme** [comment]
Hi @skade,

zunächst Danke, dass du mich darauf aufmerksam gemacht hast. War eine kleine Nacht- und Nebel-Aktion, da habe ich leider nicht so sehr drauf geachtet. :(

Ich habe die Attributions nun hinzugefügt und das MIT License File gelöscht.

Die Änderungen sind online: https://dresden-code-of-conduct.org

Magst du nochmal drüber schauen, bevor ich das Issue schließe.

Ich wollte noch fragen, ob du vll. an einer Verlinkung der beiden Seiten (Berlin CoC <> Dresden CoC) interessiert bist? Vll. unter der Headline "Community Partners" o.ä.?

Nochmals Danke, auch für die tolle Arbeit!

Beste Grüße,
Holger

**Comment by skade** [comment]
Hi Holger,

kein Problem :). Ich würde an der Stelle den Berlin Code of Conduct auch nennen, da alle Übersetzungen und Änderungen auf uns (und Freunde aus der Community) zurück gehen.

Ansonsten kooperieren wir gerne, über die Form müsste ich mal mit der Maintainer-Gruppe reden.

Danke für die schnelle Antwort (und Entschuldigung für meine späte).

Mit besten Grüßen,
Florian

**Comment by hollodotme** [comment]
@skade Ich habe nun die Maintainer, Freunde und Community des Berlin CoC mit genannt bei den Attributions. Der Berlin CoC ist auch verlinkt. Nochmals Danke für deine Unterstützung.
