### ISSUE TITLE
C++ Usergroup Dresden & Dresden Weekly

### ISSUE THREAD

**Issue by arBmind** [dresden-community/dresden-code-of-conduct.org#2]
Hi,

Danke für das aufsetzen des Code of Conducts für Dresden. Ich will das gerne unterstützen.

## C++ Usergroup Dresden

![cpp_usergroup_dresden_logo_530](https://user-images.githubusercontent.com/44107/33949429-e2598eb0-e029-11e7-8e09-6a6c73c31a41.png)

https://cpp-ug-dresden.blogspot.de
https://www.meetup.com/cpp-ug-dresden
@cppugdd

## Dresden Weekly

![hacking](https://user-images.githubusercontent.com/44107/33949468-faac4688-e029-11e7-9d28-6987527857a1.jpg)

https://www.meetup.com/Dresden-Weekly
@ddweekly

---
Aktuell bin ich bei beiden der Ansprechpartner.

Andreas Reischuck
+49 179 8085150
@arbmind

Ich denke man sollte die Ansprechpartner direkt auf der Webseite benennen. (Wie bei http://berlincodeofconduct.org/)
Logos kann ich gerne noch anhängen.

**Comment by hollodotme** [comment]
Hi @arBmind, vielen Dank für die Unterstützung!

Ja, bitte häng mal die Logos noch an dann kann ich es gleich fertig machen.

Das mit den Ansprechpartnern ist eine gute Idee, werde ich mit aufnehmen.

**Comment by arBmind** [comment]
@hollodotme ok, Bilder hab ich ergänzt. Sag wenn du da eine andere Auflösung magst.

Wäre natürlich cool, wenn ich das gleich morgen auf dem Weihnachts C++ UG Treffen ankündigen kann.

**Comment by hollodotme** [comment]
On it! ;)

**Comment by hollodotme** [comment]
So, alles erledigt. Nochmals vielen Dank! 
Ich schick auch gleich noch einen Tweet raus.

**Comment by arBmind** [comment]
Danke für das schnelle Umsetzen! Sieht gut aus.
